
# Tagged releases of Python docker images can be found at:
# https://hub.docker.com/r/library/python/tags/
#image: docker:20.10.10

#services:
#  - docker:20.10.10-dind

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CI_REGISTRY_IMAGE: "mtbc_package"
  CI_REGISTRY_PASSWORD: "Azerty4221"
  CI_REGISTRY_USER: "root"
  CI_REGISTRY_ALT: "darthos.freeboxos.fr:5050"
  DOCKER_TLS_CERTDIR: "/certs"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/



stages:
  - Static Analysis
  - Test
  - Deploy


flake8:
  #when: manual
  stage: Static Analysis
  before_script:
    - python --version  # Print out python version for debugging
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install flake8
    - pip install -r requirements.txt
  script:
  - flake8  --max-line-length=150 python/*.py

unittest:
  #when: manual
  stage: Test
  before_script:
    - python --version  # Print out python version for debugging
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
  - cd python && python -m unittest -v test_mtbc.TestMtbcRandom
  


deploy_by_ssh:
  stage: Deploy
  when: manual
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
  - eval $(ssh-agent -s)
  - ssh-keyscan 192.168.1.198 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh root@192.168.1.198 "apt-get install -y git"
  - ssh root@192.168.1.198 "cd mtbc_package && git pull https://root:Azerty4221@darthos.freeboxos.fr/gitlab/gitlab-instance-15e1ca69/mtbc_package.git"
  - ssh root@192.168.1.198 "cd mtbc_package && pip3 install -r requirements.txt"
