version: "3.6"


services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - ./python/alignement:/code/python/alignement
        - ./python/nj_tree:/code/python/nj_tree
        - ./:/code/python
    ports:
        - "80:80"
