version: "3.6"


services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code/
    ports:
      - "80:80"
    environment:
      - MONGO_HOST=mongodb


  mongodb:
    image: mongo:5.0

    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

