version: "3.6"


services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - ./python/alignement:/code/python/alignement
        - ./python/tree:/code/python/tree
    ports:
        - "80:80"
